name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate pretty-printed assets
        run: yarn dist

      - name: Generate minified assets
        run: yarn prod

      - name: Compress pretty-printed assets
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ github.ref_name }}.zip dist

      - name: Compress minified assets
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ github.ref_name }}.min.zip prod

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.ref_name }}.zip
            ${{ github.ref_name }}.min.zip
